#pragma once

// GLFW key codes
#define NC_KEY_SPACE         32
#define NC_KEY_APOSTROPHE    39
#define NC_KEY_COMMA         44
#define NC_KEY_MINUS         45
#define NC_KEY_PERIOD        46
#define NC_KEY_SLASH         47
#define NC_KEY_0             48
#define NC_KEY_1             49
#define NC_KEY_2             50
#define NC_KEY_3             51
#define NC_KEY_4             52
#define NC_KEY_5             53
#define NC_KEY_6             54
#define NC_KEY_7             55
#define NC_KEY_8             56
#define NC_KEY_9             57
#define NC_KEY_A             65
#define NC_KEY_B             66
#define NC_KEY_C             67
#define NC_KEY_D             68
#define NC_KEY_E             69
#define NC_KEY_F             70
#define NC_KEY_G             71
#define NC_KEY_H             72
#define NC_KEY_I             73
#define NC_KEY_J             74
#define NC_KEY_K             75
#define NC_KEY_L             76
#define NC_KEY_M             77
#define NC_KEY_N             78
#define NC_KEY_O             79
#define NC_KEY_P             80
#define NC_KEY_Q             81
#define NC_KEY_R             82
#define NC_KEY_S             83
#define NC_KEY_T             84
#define NC_KEY_U             85
#define NC_KEY_V             86
#define NC_KEY_W             87
#define NC_KEY_X             88
#define NC_KEY_Y             89
#define NC_KEY_Z             90
#define NC_KEY_ESCAPE        256
#define NC_KEY_ENTER         257
#define NC_KEY_TAB           258
#define NC_KEY_BACKSPACE     259
#define NC_KEY_RIGHT         262
#define NC_KEY_LEFT          263
#define NC_KEY_DOWN          264
#define NC_KEY_UP            265
#define NC_KEY_F1            290
#define NC_KEY_F2            291
#define NC_KEY_F3            292
#define NC_KEY_F4            293
#define NC_KEY_F5            294
#define NC_KEY_F6            295
#define NC_KEY_F7            296
#define NC_KEY_F8            297
#define NC_KEY_F9            298
#define NC_KEY_F10           299
#define NC_KEY_F11           300
#define NC_KEY_F12           301
#define NC_KEY_LEFT_SHIFT    340
#define NC_KEY_LEFT_CONTROL  341
#define NC_KEY_LEFT_ALT      342

// Mouse buttons
#define NC_MOUSE_BUTTON_LEFT   0
#define NC_MOUSE_BUTTON_RIGHT  1
#define NC_MOUSE_BUTTON_MIDDLE 2